language: node_js
node_js:
- 0.8

branches:
  only:
  - master

before_script:
- npm run build

after_script:
- git status
- git config user.name "tonyfast"
- git config user.email "tony.fast@gmail.com"
- git checkout master
- git add .
- git commit -m "Build Coffeescript"
# View status in travis dashboard
- git status
- git push "https://${GH_TOKEN}@github.com/tonyfast/d3.template.git" master:master

env:
  global:
    secure: CiHPKJGq+ydsnXmwW+oO0tYpV5QU5dB1iRHX5jwFAfKAjcr1Bb24QsVkkkOgAS+D8x5a256AlpHtuCFRUzlBUvvABzPfAL15GXyXk/cCMfRa6+F89ElWr5sX5M5k/58iWHBXo3yTdvPhS4wwRCCWkSoeH0/cjOMGaOKpJ/7jcsQ=
